name: JS Lint

on: [pull_request]

jobs:
  test:
    name: JS Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: run npm ci

      - name: ESLint
        run: npm run lint:js

      - name: Stylelint
        run: npm run lint:css