name: JS Lint

on: [pull_request]

jobs:
  test:
    name: JS Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Cache npm packages
        id: npm_cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.npm_cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: ESLint
        run: npm run lint:js

      - name: Stylelint
        run: npm run lint:css