name: PHPUnit

on: 
  pull_request:
    paths:
      - 'class/**'
      - 'tests/**'
      - 'admin-bar-tools.php'

env:
  CACHE_TAG: v1
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install composer packages & cache vendor directory
        uses: ./.github/actions/vendor-dependencies
        with:
          cache_tag: ${{ env.CACHE_TAG }}

      - name: Setup Node.js
        uses: ./.github/actions/setup-nodejs

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ${{ github.workspace }}/package-lock.json
      
      - name: Install npm packages & cache node_modules
        uses: ./.github/actions/node_modules-dependencies
        with:
          cache_tag: ${{ env.CACHE_TAG }}

  test:
    name: PHPUnit
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.0', '8.1', '8.2']
        wp-version:  ['master', '6.2', '6.1', '6.0', '5.9']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup -> PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xdebug, dom

      - name: Setup Node.js
        uses: ./.github/actions/setup-nodejs

      - name: Install composer packages & cache vendor directory
        uses: ./.github/actions/vendor-dependencies
        with:
          cache_tag: ${{ env.CACHE_TAG }}

      - name: Install npm packages & cache node_modules
        uses: ./.github/actions/node_modules-dependencies
        with:
          cache_tag: ${{ env.CACHE_TAG }}

      - name: TypeScript compile
        run: npm run build

      - name: Generate .wp-env.override.json
        run: |
          echo '{"config": {},"core": "WordPress/WordPress#${{ matrix.wp-version }}","env": {},"mappings": {},"phpVersion": "${{ matrix.php-version }}","plugins": ["."],"themes": []}' > .wp-env.override.json

      - name: Start wp-env
        run: npm run wp-env start

      - name: Run test suite
        run: npm run test:env