name: PHPUnit

on:
  push:
    tags:
      - 'v*'

jobs:
  upload:
    name: Upload to WordPress Directory
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: